### ISSUE TITLE
Keyword definition & Variable definition not found error

### ISSUE THREAD

**Issue by Zabi-Py** [AmailP/robot-plugin#52] opened 2017-10-02 05:24 UTC
1. Keyword definition not found error is being raised for SeleniumLibrary keywords. 
2. Autocomplete is also not working. 
3. Variable definition not found error is raised even after importing resource file.
Can you please resolve this issue and update the plugin accordingly ? 

RobotFramework = 3.0.2, robotframework-seleniumlibrary = 3.0.0.b3

**Comment by Zabi-Py** [comment] 2017-10-02 05:25
![error](https://user-images.githubusercontent.com/30861354/31065096-40052b30-a760-11e7-9d27-24e499da99d7.png)

**Comment by michaelzoro** [comment] 2017-12-07 10:13
I have the same issue. After down-grading to the former Selenium2Library 'robotframework-selenium2library (1.8.0)' all worked fine. I.e. there is some kind of incompatibility of the plugin with 'robotframework-seleniumlibrary (3.0.0)'.

**Comment by r-roos** [comment] 2017-12-08 15:57
having the same issue

**Comment by alalakina** [comment] 2017-12-19 11:45
having the same issue 
robotframework=3.0.2, robotframework-seleniumlibrary=3.0.1

**Comment by huima** [comment] 2017-12-29 17:13
Same issue with robot 3.0.2

**Comment by OliaVk** [comment] 2018-02-05 04:18
Experienced the same issue with ExtendedSelenium2Library. The fix for me was to use Selenium2Library. In the original question @Zabi-Py imports SeleniumLibrary, using Selrnium2Library instead, might solve the issue.

**Comment by MarkJB** [comment] 2018-02-12 15:41
SeleniumLibrary now uses the Dynamic Library API

> Only differences between static and dynamic libraries are how Robot Framework discovers what keywords a library implements

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dynamic-library-api

**Comment by teone** [comment] 2020-04-29 23:40
Same issue with Golang:
<img width="1014" alt="Screen Shot 2020-04-29 at 4 37 25 PM" src="https://user-images.githubusercontent.com/3929466/80657257-fb2baf80-8a37-11ea-8c60-a2c7f29be8d2.png">

`Keywords` from local libraries work perfectly

Robot Framework is installed and the IDE is configured to point to the correct python interpreted

**Comment by AmailP** [comment] 2021-05-02 21:28
Closing as a duplicate of #38

**Closed by AmailP** 2021-05-02 21:28 UTC
Labels: help wanted
