### ISSUE TITLE
Unable to find keywords

### ISSUE THREAD

**Issue by chethanha** [AmailP/robot-plugin#109] opened 2021-02-02 08:49 UTC
I have installed
1.Robot framework 3.2.2
3.Robot framework selenium library 
![image](https://user-images.githubusercontent.com/77769216/106574971-66873e00-64f0-11eb-9262-93866a885370.png)

but unable to find keyword.

![image](https://user-images.githubusercontent.com/77769216/106575075-80c11c00-64f0-11eb-81ef-f2b0a040e0e5.png)

**Comment by AmailP** [comment] 2021-05-02 21:27
Closing as a duplicate of #38

**Closed by AmailP** 2021-05-02 21:27 UTC
